### ISSUE TITLE
403 forbidden error when visting test page

### ISSUE THREAD

**Issue by tomxxcd** [adsr/rw.rs#180]
<img width="430" alt="Screen Shot 2023-06-07 at 11 25 19 PM" src="https://github.com/adsr/rw.rs/assets/66445023/5e7dedff-2ddb-4f95-a1d4-d722fa5dcbb0">

Gives me an error when I try to visit the public_html test page, any fixes?

**Comment by adsr** [comment]
Strange. While investigating this I discovered 6 other users that have the same issue despite having the correct perms. I confirmed the underlying syscall is hitting EACCESS. I'll try to fix this and get back to you. Thanks for reporting.

**Comment by adsr** [comment]
I thought for sure I'd checked this earlier but your home directory (and the other users') has 700 perm bits. If you change it to 755 (or at least 701) it should work.

I presume 700 was used for privacy. There's probably a way to make that happen without sacrificing public_html. I can look into that if people are interested.

**Comment by Veraellyunjie** [comment]
Same here, and I became a member January 2024 - quite after this issue surfaced.
`chmod o+x ~` did help.

Please update https://github.com/adsr/rw.rs#quickstart
Also please consider removing `$` in each quickstart line.

Quickstart now:
```
...
$ # Make your web page at http://rw.rs/~<you>
$ mkdir ~/public_html
$ echo hello internet >~/public_html/index.html
...
```

Quickstart desired:
```
...
# Make your web page at http://rw.rs/~<you>
mkdir ~/public_html
echo hello internet >~/public_html/index.html
chmod o+x ~
...
```

**Comment by adsr** [comment]
@Veraellyunjie can you review https://github.com/adsr/rw.rs/pull/217? Thanks.
