### ISSUE TITLE
Error while trying SSHing

### ISSUE THREAD

**Issue by adlermedrado** [adsr/rw.rs#229]
Hello.

I'm getting an error while trying to SSHing into rw.rs, the error message is below:

amedrado@rw.rs: Permission denied (publickey).

I am using the correct ssh key.

Thanks in advance.

**Comment by adsr** [comment]
Hi @adlermedrado can you make a PR to rename `users/amedrado/rw.rs.pub` to `users/amedrado/authorized_keys`? Sorry I missed that.

**Comment by adlermedrado** [comment]
Done.

**Comment by adlermedrado** [comment]
Thank you.

**Comment by adsr** [comment]
No problem. A cron should fix your account in the next 10 minutes or so. Feel free to reopen if you have any trouble.
