### ISSUE TITLE
Allow users to choose login shell

### ISSUE THREAD

**Issue by ansimita** [adsr/rw.rs#24]
Please refer to [this solution](https://serverfault.com/questions/202468/changing-the-shell-using-chsh-via-the-command-line-in-a-script/435539#435539).

**Comment by adsr** [comment]
Hm I'll look into this. I don't understand the solution you linked. At first glance it looks like it gives everyone root.

**Comment by ansimita** [comment]
I think that it's basically creating a group in which users can invoke `chsh` without entering a password. You can try emulating in a separate VM.

Feel free to evaluate other approaches.

P.S. Thanks for looking into all of this.

**Comment by adsr** [comment]
It turns out filenames in `/etc/pam.d/` are important. `/etc/pam.d/chsh` only applies to chsh. That is unusual for `.d` conf dirs. From `man 5 pam.conf`:

```
       The syntax of files contained in the /etc/pam.d/ directory, are identical except for the absence of any service field. In
       this case, the service is the name of the file in the /etc/pam.d/ directory. This filename must be in lower case.
...
       The service is typically the familiar name of the corresponding application: login and su are good examples. The
       service-name, other, is reserved for giving default rules. Only lines that mention the current service (or in the absence
       of such, the other entries) will be associated with the given service-application.

```
